#SPDX-License-Identifier: MIT-0
---
# vars file for zsh
user_name: "{{ ansible_user }}"
user_home: "/home/{{ ansible_user }}"
zsh_theme: "agnoster"
zsh_user: "{{ ansible_user }}"
zsh_home: "/home/{{ ansible_user }}"